clone_folder: C:\repo

matrix:
  fast_finish: true

environment:
  global:
    DOWNLOAD_DIR: _download_cache
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Tools\curl\bin;C:\msys64\usr\bin;C:\Program Files (x86)\Inno Setup 5
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VER: "14"
      PLATFORM: "x86"
      PYTHON: C:\Python36\python.exe

build_script:
  - "%PYTHON% --version"
  # Print PATH variable.
  - set PATH
  - for /f %%i in ('%PYTHON% -c "from rednotebook import info; print(info.version)"') do set VERSION=%%i
  - set VERSION
  - cd win

  # Install Python 3.4 and GTK 3.18 stack.
  - curl -Lo python34.tar.gz https://www.dropbox.com/s/3wu38oluushvqan/python34.tar.gz?dl=1
  - tar -xzf python34.tar.gz
  - move Python34 C:\Python34
  - set PATH=%PATH%;C:\Python34\Lib\site-packages\gnome
  - set PYTHON=C:\Python34\python.exe

  # Install other dependencies.
  - "%PYTHON% -m pip install -U pip==19.0.3 wheel"
  - "%PYTHON% -m pip install -r requirements.txt"

  # Sanity check with dummy app.
  - "%PYTHON% sampleapp.py"
  - "%PYTHON% -m PyInstaller --debug=all --additional-hooks-dir=. sampleapp.py"
  # Use clean PATH to check that everything has been copied correctly.
  - cmd /C "set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem && dist\sampleapp\sampleapp.exe"

  # Create executable.
  - "%PYTHON% -m PyInstaller --workpath=C:/build --distpath=C:/ rednotebook.spec"
  - "%PYTHON% build-translations.py C:/dist/share/locale"
  - tar -czf rednotebook.tar.gz -C /c/ dist

  # Build installer.
  - iscc /Qp /dREDNOTEBOOK_VERSION="%VERSION%" rednotebook.iss

  # Artifacts have to live under "clone_folder".
  - move rednotebook.tar.gz C:\repo\rednotebook-"%VERSION%".tar.gz
  - move C:\rednotebook.exe C:\repo\rednotebook-"%VERSION%".exe

artifacts:
  - path: rednotebook-*.tar.gz
    name: Standalone Windows executable
  - path: rednotebook-*.exe
    name: Windows installer

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: "UT6jPkpy8U/qTN+8LF7hPsJ/cHWlt+7a+wO2Ou2iKYImeBxAV4OY6Gt3Y0v5/ZuL"
  artifact: /rednotebook-.*\.exe/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

cache:
  - '%DOWNLOAD_DIR%'

test: off
